// This file is @generated by prost-build.
/// Params defines the parameters for the module.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Params {
    #[prost(uint64, repeated, tag = "1")]
    pub fee_tiers: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "2")]
    pub max_true_taker_spread: ::prost::alloc::string::String,
}
impl ::prost::Name for Params {
    const NAME: &'static str = "Params";
    const PACKAGE: &'static str = "neutron.dex.v2";
    fn full_name() -> ::prost::alloc::string::String {
        "neutron.dex.v2.Params".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/neutron.dex.v2.Params".into()
    }
}
